# Generated by Django 3.2.9 on 2021-11-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0005_alter_donation_pick_up_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
