# Generated by Django 3.2.9 on 2021-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0006_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='taken_check_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
